# Curso Deep Learning - Exercícios Python Avançado

Este é um notebook Jupyter contendo exercícios de programação Python Avançado utilizando programação orientada a objetos e iteradores.

Esta lista de exercício é um guia de estudo. Para fazer os exercícios será necessário estudar o Python e consultar documentação e tutoriais disponíveis na Internet.

### Python

Estes exercícios devem ser feitos com o Python 3.
Recomenda-se utilizar o Google Colab para fazer esses exercícios (https://colab.research.google.com/).

### Jupyter notebook

Este é um Notebook Jupyter. Um notebook Jupyter é uma mistura de linguagem Markdown para formatar texto (como uma Wiki) e um programa Python. É muito usado entre as pessoas que trabalham com Data Science e Machine Learning em Python.

Se utilizar o Jupyter notebook, instale o Jupyter nbextensions que é um conjunto de ferramentas auxiliares. Habilite o "Table of Contents" do nbextensions para que este notebook fique itemizado. Para o Google Colab, não é possível instalar o nbextensions.

Você pode adicionar quantas células quiser neste notebook para deixar suas respostas bem organizadas.

Os seguintes exercícios devem usar apenas o pacote Python e NumPy.
Não se deve utilizar nenhum outro pacote adicional.


## Escreva seu nome

In [1]:
print('Meu nome é: Renato César Alves de Oliveira')

Meu nome é: Renato César Alves de Oliveira


In [2]:
import numpy as np

# Programação Orientada a Objetos

Documentação oficial: https://docs.python.org/3/tutorial/classes.html

Forma clássica de definição de uma função:

In [3]:
data = np.array([13, 63, 5, 378, 58, 40])

def avg(d):
    return sum(d)/len(d)
    
avg(data)

92.83333333333333

## Definição da classe, variáveis, inicialização e método

Definição da classe `MyAvg`, contendo duas variávels: `id` (compartilhada) e `d`. A classe possui os métodos de inicialização (`__init__`) e `avg`.

- **Classe** é uma forma de definir um tipo abstrato de dados
- **Instância** de uma classe é chamada **objeto**
- Operadores ou funções de uma classe são chamados **métodos**
- **Variáveis de instância** são variáveis associadas à instância
- **Variáveis de classe** são variáveis compartilhada com todas as instâncias da classe

O nome de uma classe é usualmente escrita usando *Camel case* enquanto que métodos são
escritos com caixa baixa.

In [4]:
class MyAvg:
    id = 0.33                # variável compartilhada com todas as instâncias
    
    def __init__(self,data):
        self.d = data        # variável associada a cada instância 
        
    def avg(self): # método para calcular a média
        return sum(self.d) / len(self.d)

Objetos `a` e `b` são instâncias da classe `MyAvg`.
Instanciar uma classe é inicializá-la através da chamada ao método __init__:

In [5]:
a = MyAvg(data)
b = MyAvg(2 * data)

Aplicação do método `avg()`, retorna a média dos dados dos objetos a e b:

In [6]:
print(a.avg())
print(b.avg())

92.83333333333333
185.66666666666666


In [7]:
# Imprima os valores dos dados associados aos objetos a e b:
print(a.d)
print(b.d)

[ 13  63   5 378  58  40]
[ 26 126  10 756 116  80]


In [8]:
# Imprima a variável compartilhada `id` de cada objeto a e b:
print(a.id)
print(b.id)

0.33
0.33


## Herança de classe

In [9]:
class MyAvgStd(MyAvg):
    def var(self): # método adicional para calcular a variância
        u = self.avg()
        return np.sqrt(np.sum((self.d - u)**2) / len(self.d))

In [10]:
c = MyAvgStd(data)

In [11]:
print('media:', c.avg())
print('variancia:', c.var())

media: 92.83333333333333
variancia: 129.294775180163


In [12]:
# imprima os dados associados ao objeto c e a sua variável compartilhada id
print(c.d)
print(c.id)

[ 13  63   5 378  58  40]
0.33


### Exercício: convertendo a função `split` na classe `C_Split`

Implemente a classe `C_Split` para ter a mesma funcionalidade da função `split` feita no notebook de estudo de NumPy

In [40]:
class C_Split():
    def __init__(self,d):
        self.d = d
    def split(self, split_factor):
        nlines = self.d.shape[0]
        rows_t = int(split_factor*nlines)
        train, val  = self.d[:rows_t,:],self.d[rows_t:nlines,:]
        return train, val

In [41]:
# Entrada, matriz contendo 10 amostras e 9 atributos
aa = np.arange(90).reshape(10,9)
data_train_val = C_Split(aa)
train, val = data_train_val.split(0.8)
print('t=\n', train)
print('v=\n', val)

t=
 [[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]
 [27 28 29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42 43 44]
 [45 46 47 48 49 50 51 52 53]
 [54 55 56 57 58 59 60 61 62]
 [63 64 65 66 67 68 69 70 71]]
v=
 [[72 73 74 75 76 77 78 79 80]
 [81 82 83 84 85 86 87 88 89]]


## Classe com métodos `__len__` e `__getitem__`

Uma classe com métodos `__len__` e `__getitem__` permite que os objetos possam ser indexados e calculado o seu número de elementos.

Veja o exemplo a seguir:

In [42]:
class Word():
    def __init__(self, phrase):
        self.wordlist = phrase.split() # separa frase em uma lista de palavras
    
    def __len__(self):
        return len(self.wordlist)
    
    def __getitem__(self, x):
        return self.wordlist[x]

In [43]:
frase = 'Esta frase é formada por 7 palavras'
palavras = Word(frase)

In [44]:
palavras[3]  # permite a indexação do objeto

'formada'

In [45]:
print(len(palavras))

7


### Exercício para indexar elementos de um dicionário

Um dicionário em Python não é indexado. Por exemplo seja o dicionário `d` a seguir.
Não é possível indexar d[0] ou d[1] para buscar o primeiro ou segundo par (chave:valor).

In [46]:
d = {'a':1, 'b': 2}

Implementar uma classe que receba um dicionário e permita que ele possa ser indexado.
Para converter um dicionário em uma lista de pares, use:

In [47]:
list(d.items())

[('a', 1), ('b', 2)]

Complete a definição da classe `dicdata` a seguir para que um dicionário possa ser
indexado:

In [50]:
class DicData():
    def __init__(self, dic):
        self.dic = d
        
    def __len__(self):
        return len(self.dic)
        
    def __getitem__(self, x):
        return list(self.dic.items())[x]

In [52]:
dd = DicData(d)
print(len(dd))
print(dd[0])

2
('a', 1)


## Iteradores

Iteradores são uteis para serem usados em estruturas do tipo `for a in b:`.

Listas em Python são consideradas iteráveis, pois podem ser utilizadas nessa estrutura:

In [53]:
for i in ['a', 'b', 'c']:
    print(i)

a
b
c


O método do `range()` do python também é um iterável:

In [54]:
for i in range(3):
    print(i)

0
1
2


É possível acessar o iterador destas estruturas utilizando o método `iter()` do Python e então é possível percorrer seus elementos utilizado `next()`:

In [57]:
lista = ['a', 'b', 'c']
iterador = iter(lista)
print('tipo de iterador:', type(lista))
print('tipo de iterador:', type(iterador))
print(next(iterador))

tipo de iterador: <class 'list'>
tipo de iterador: <class 'list_iterator'>
a


O acesso de iteradores é sequencial e após o ultimo elemento uma exceção é levantada indicando o fim do iterador.
Descomente o último `next` e veja o tipo da exceção que acontece.

In [58]:
print(next(iterador))
print(next(iterador))
#print(next(iterador))

b
c


## Criando objetos iteráveis

Para implementar um objeto iterador é preciso escrever um método `__next__()` para a classe e para que ele seja acessível como iterável também é necessário escrever um método `__iter__()`: 

In [59]:
class WordIterator():
    def __init__(self, phrase):
        self.words = phrase.split()
        
    def __iter__(self):
        self.iter_index = 0
        return self
    
    def __next__(self):
        if self.iter_index < len(self.words):
            i = self.iter_index
            self.iter_index += 1
            return self.words[i]
        else:
            raise StopIteration()

A classe acima é um iterador e é iterável. 

No método `__iter__()` reiniciamos o índice inicial para o iterador e retornamos o próprio objeto (um iterador).

No método `__next__()` retornamos a palavra do índice atual ou a exceção de parada, caso seja o fim.

In [60]:
frase = 'Esta frase é formada por 7 palavras'
iterador_de_palavras = WordIterator(frase)

In [61]:
for palavra in iterador_de_palavras:
    print(palavra)

Esta
frase
é
formada
por
7
palavras


### Exercício com iterador

Crie uma classe `DictIterator` que permita varrer os itens de um dicionário utilizando o `for`

In [62]:
class DictIterator():
    def __init__(self, dict):
        self.d = list(dict.items())
    def __iter__(self):
        self.iter_index = 0
        return self
    def __next__(self):
        if self.iter_index < len(self.d):
            i = self.iter_index
            self.iter_index += 1
            return self.d[i]
        else:
            raise StopIteration()

In [64]:
d = {'a':1,'b': 2, 'c': 3}
d_iter = DictIterator(d)
for i in d_iter:
    print(i)

('a', 1)
('b', 2)
('c', 3)


## Objeto como função

É possível declarar uma classe contendo um objeto possa ser chamado (*callable object*).
Para isso, a classe deve conter o método `__call__`. Veja o exemplo a seguir:

In [23]:
class Scale():
    def __init__(self, w):
        self._w = w
    def __call__(self, x):
        return x * self._w

In [24]:
s = Scale(100.)
print(s(5))


500.0


### Exercício de classe contendo objeto chamável

Defina uma classe herdada da classe `Scale` que permita modificar a variável `self._w`.

In [25]:
class AjustaPeso(Scale):
    def wset (self, x):
        self._w = x

In [26]:
ap = AjustaPeso(100.)
print(ap(5))

500.0


In [27]:
ap.wset(10)
print(ap(5))

50


# Fim do notebook