# Curso Deep Learning - Exercício pré-curso NumPy

Este é um notebook Jupyter contendo exercícios de programação matricial utilizando o Python e biblioteca NumPy.
Estes exercícios servem para verificar os conhecimentos da linguagem Python para manipulação matricial com a biblioteca NumPy.

Esta lista de exercício é um guia de estudo. Para fazer os exercícios será necessário estudar o NumPy e consultar documentação e tutoriais disponíveis na Internet.

### Python

Recomenda-se utilizar o Google Colab para fazer esses exercícios (https://colab.research.google.com/) pois o curso será oferecido nele. A vantagem do Colab é ser uma plataforma gratuito que permite o uso de GPU, fundamental para a realização dos exercícios de deep learning.


### Jupyter notebook

Este é um Notebook Jupyter. Um notebook Jupyter é uma mistura de linguagem Markdown para formatar texto (como uma Wiki) e um programa Python. É muito usado entre as pessoas que trabalham com Data Science e Machine Learning em Python.


Você pode adicionar quantas células quiser neste notebook para deixar suas respostas bem organizadas.

# Exercícios usando NumPy

Os seguintes exercícios devem usar apenas o pacote NumPy.
Não se deve utilizar nenhum outro pacote adicional.
O NumPy é o pacote que faz o Python apropriado para programação científica.
A programação eficiente de matrizes multidimensionais (arrays ou tensores) é
feita através do conceito de programação matricial que evita o uso de laços
e iterações nos elementos da matriz.

Existem vários exemplos de uso de NumPy no conjunto de
notebooks tutorias disponíveis no GitHub:
- https://github.com/robertoalotufo/ia898/blob/master/master/0_index.ipynb

## Preencha o seu nome

In [1]:
print('Meu nome é: Renato César Alves de Oliveira')

Meu nome é: Renato César Alves de Oliveira


In [2]:
import numpy as np

Veja como é possível criar um array unidimensional e depois reformatá-lo para ser acessado como array bidimensional:

In [3]:
array = np.arange(10)
print(array)
print(array.shape)

[0 1 2 3 4 5 6 7 8 9]
(10,)


In [4]:
A = np.arange(24).reshape(4, 6)
print(A)
print(A.shape)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
(4, 6)


### Exercício: imprimindo rows, cols, dimensions, shape and datatype

In [5]:
# imprima o número de linhas de A
print(A.shape[0])
# imprima o número de colunas de A
print(A.shape[1])
# imprima o número de dimensões de A
print(A.ndim)
# imprima o shape de A:
print(A.shape)
# imprima o tipo de dados (dtype) dos elementos de A:
print(A.dtype)

4
6
2
(4, 6)
int32


### Reshape

In [6]:
# Seja o vetor unidimensional a:
a = np.array([1, 2, 3, 4])
print(a, a.shape)

[1 2 3 4] (4,)


### Exercício: Converta o vetor unidimensional a em uma matriz vetor coluna (4 linhas e 1 coluna) utilizando reshape

In [7]:
a = a.reshape(4,1)
print(a)

[[1]
 [2]
 [3]
 [4]]


## Exercício: Cópia por referência, cópia rasa e cópia profunda

Explique a diferença entre estes 3 tipos de cópias e dê um exemplo de cada uma.
O conceito aqui é em relação ao NumPy e não ao Python.
**Resposta**:

Na cópia por referência (x = a), a variável x passa a apontar para o mesmo objeto que a variável a, sendo assim, no exemplo abaixo, a, x, y e z referenciam o mesmo objeto (ou atributos do mesmo objeto) e, por isso, quando quando quaisquer um deles são modificados, o mesmo objeto está sendo modificado.

Já a variável zz é uma cópia rasa de a, ou seja, é um objeto totalmente diferente e independente de a e quando é modificado não afeta o mesmo objeto referenciado por a.

A cópia profunda (deepcopy()) não esá sendo usado abaixo, e é aplicável quando um objeto referencia uma  concatenação de objetos, nesse caso, a cópia profunda cria uma coóia tanto do objeto em como de suas referências. Já a cópia rasa só cria uma cópia do objeto, mantendo iguais possíveis referências a outros objetos.


In [10]:
# Indique para cada uma das expressões a seguir se a cópia é por referência, rasa ou profunda
x = a # cópia por referencia
y = a[:2] # cópia por referencia
print(y)
z = a.reshape(4, 1) # cópia por referencia
zz = a.copy() # cópia rasa

[[1]
 [2]]


In [11]:
# Explique o valor dos resultados:
z[0,0] = 5
print(a) # explique:
y[1] = 6
print(a) # explique:
zz[0] = 7
print(a) # explique:

print(id(a))
print(id(z))
print(id(x))
print(id(y))
print(id(zz))

[[5]
 [2]
 [3]
 [4]]
[[5]
 [6]
 [3]
 [4]]
[[5]
 [6]
 [3]
 [4]]
2385593813792
2385593857088
2385593813792
2385593814272
2385593857168


## Operações aritméticas

In [43]:
B = A + 10
B

array([[10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33]])

### Array binário (booleano)

#### Exercício: Crie uma matriz booleana C com True nos elementos de B menores que 18 (não utilize loop explícito)

In [44]:
C = B<18  # Modifique o código aqui.
print(C)

[[ True  True  True  True  True  True]
 [ True  True False False False False]
 [False False False False False False]
 [False False False False False False]]


## Indexação booleana

### Exercício: explique o comando a seguir de indexação booleana

In [45]:
A[B < 18]

array([0, 1, 2, 3, 4, 5, 6, 7])

Explicação: Constrói um array de inteiros cujos elementos correspondem aos indexes das posições (em uma dimensão) dos elemtos de B que são menores que 18.

Veja um programa que cria matriz D_loop a partir da matriz B, porém trocando os elementos menores que 18 por seus valores negativos

In [46]:
D_loop = B.copy()
for row in np.arange(B.shape[0]):
    for col in np.arange(B.shape[1]):
        if B[row,col] < 18:
            D_loop[row,col] = - B[row,col]
print(D_loop)

[[-10 -11 -12 -13 -14 -15]
 [-16 -17  18  19  20  21]
 [ 22  23  24  25  26  27]
 [ 28  29  30  31  32  33]]


### Exercício: Substitua o programa acima por uma única linha sem loop, utilizando indexação booleana e evitando o uso de `where`

In [51]:
D = np.where(B <18, -B, B) 
print(D)

[[-10 -11 -12 -13 -14 -15]
 [-16 -17  18  19  20  21]
 [ 22  23  24  25  26  27]
 [ 28  29  30  31  32  33]]


## Redução de eixo: soma

Operações matriciais de redução de eixo são muito úteis e importantes.
É um conceito importante da programação matricial.

Estude o exemplo a seguir:

In [62]:
print(A)
print(A.shape)
As = A.sum(axis=0)
print(As)
print(As.shape)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
(4, 6)
[36 40 44 48 52 56]
(6,)


### Exercício: Explique o funcionamento da soma por redução de eixo. Qual foi a dimensão que desapareceu?

Resposta: Soma todos os elementos do eixo indicado e o resultado da soma corresponde aos elemetos do eixo que permanece. No exemplo acima, as linhas (eixo 0) são condensadas em uma unica linha e a soma dos elementos das linhas de cada coluna são os elementos que que permanecem nas colunas.

### Exercício: calcule o valor médio do array A

In [64]:
print(A.mean())

11.5


### Exercício: calcule o valor médio das linhas de A:

In [67]:
print(A.mean(axis=1))

[ 2.5  8.5 14.5 20.5]


## Broadcasting

### Exercício: O que significa o conceito de broadcasting em NumPy?

Resposta: Broadcasting se refere a maneira que numpy, ao realizar operções entre matrizes, acomoda matrizes com dimensões diferentes e, sendo assim, não é necessário, por exemplo, que uma soma de matrizes ambas tenham as mesmas dimensões, contanto que ao menos uma delas tenha uma dimensão 1.

### Exercício: Usando o conceito de broadcast, mude o shape do vetor a para que o broadcast possa ocorrer quando fizermos G = A + a

In [71]:
a = np.arange(4)
a = a.reshape(4,1)
print(a)
G = A + a
print(G)

[[0]
 [1]
 [2]
 [3]]
[[ 0  1  2  3  4  5]
 [ 7  8  9 10 11 12]
 [14 15 16 17 18 19]
 [21 22 23 24 25 26]]


## Normalização entre 0 e 1

Seja a matriz $C$ que é a normalização da matriz $A$:
$$ C(i,j) = \frac{A(i,j) - A_{min}}{A_{max} - A_{min}} $$

Em programação matricial, não se faz o loop em cada elemento da matriz,
mas sim, utiliza-se operações matriciais. Faça o exercício a seguir
sem utilizar laços explícitos:

### Exercício: Criar a matriz C que é a normalização de A, de modo que os valores de C estejam entre 0 e 1.


In [72]:
C = (A - A.min())/(A.max()-A.min())
print(C)

[[0.         0.04347826 0.08695652 0.13043478 0.17391304 0.2173913 ]
 [0.26086957 0.30434783 0.34782609 0.39130435 0.43478261 0.47826087]
 [0.52173913 0.56521739 0.60869565 0.65217391 0.69565217 0.73913043]
 [0.7826087  0.82608696 0.86956522 0.91304348 0.95652174 1.        ]]


### Exercício: Modificar o exercício anterior, porém agora faça a normalização para cada coluna de A de modo que as colunas da matriz D estejam entre os valores de 0 a 1. Dica: utilize o conceito de redução de eixo.


In [79]:
D = (A - A.min(0))/(A.max(0)-A.min(0))
print(D)
A.min(1).reshape(4,1)

[[0.         0.         0.         0.         0.         0.        ]
 [0.33333333 0.33333333 0.33333333 0.33333333 0.33333333 0.33333333]
 [0.66666667 0.66666667 0.66666667 0.66666667 0.66666667 0.66666667]
 [1.         1.         1.         1.         1.         1.        ]]


array([[ 0],
       [ 6],
       [12],
       [18]])

### Exercício: Modificar o exercício anterior, porém agora faça a normalização para cada linha de A de modo que as colunas da matriz E estejam entre os valores de 0 a 1. Dica: utilize o conceito de redução de eixo, porém mantenha o mesmo número de eixos para poder fazer broadcast.

In [80]:
E = (A - A.min(1).reshape(4,1))/(A.max(1).reshape(4,1)-A.min(1).reshape(4,1))
print(E)

[[0.  0.2 0.4 0.6 0.8 1. ]
 [0.  0.2 0.4 0.6 0.8 1. ]
 [0.  0.2 0.4 0.6 0.8 1. ]
 [0.  0.2 0.4 0.6 0.8 1. ]]


## Fatiamento em arrays (slicing)

In [81]:
# esta indexação é chamada fatiamento:
AA = A[:,1::2]
print(AA)

[[ 1  3  5]
 [ 7  9 11]
 [13 15 17]
 [19 21 23]]


### Exercício: Crie a matriz AB apenas com as linhas pares da matriz A, utilizando o conceito de fatiamento:


In [84]:
AB = A[::2,:]
print(AB)

[[ 0  1  2  3  4  5]
 [12 13 14 15 16 17]]


### Exercicío: Crie a matriz AC com mesmo shape da matriz A, porém com os elementos na ordem inversa, ou seja, trocando a ordem das linhas e das colunas.



Por exemplo, a matriz [[1, 2, 3], [4, 5, 6]] será transformada para [[6, 5, 4], [3, 2, 1]]

In [88]:
AC = np.flip(np.flip(A,0),1)
print(AC)

[[23 22 21 20 19 18]
 [17 16 15 14 13 12]
 [11 10  9  8  7  6]
 [ 5  4  3  2  1  0]]


## Produto matricial  (dot product)

### Exercício: Calcule a matriz E dada pelo produto matricial entre a matriz A e sua transposta: 
$$ E = A A^T $$

In [93]:
E = A.dot(A.T)
print(E)

[[  55  145  235  325]
 [ 145  451  757 1063]
 [ 235  757 1279 1801]
 [ 325 1063 1801 2539]]


### Exercício: Descomente a linha e explique por que a operação de multiplicação dá erro.

In [97]:
Ee = A * A.T

ValueError: operands could not be broadcast together with shapes (4,6) (6,4) 

O erro ocorre pois essa operação é uma multiplicação regular, não matricial, e, sendo assim, o numpy não consegue processar o broadcast com dimensões conflitantes.

## Matrizes multidimensionais

Em deep learning, iremos utilizar matrizes multidimensionais
que são denominados como arrays no NumPy. PyTorch usa o nome de tensor para
suas matrizes multimensionais.

Matrizes de dimensões maior que 4 são de difícil intuição. A melhor forma de lidar
com elas é observando o seu *shape*.

### 3-D array

In [109]:
F = A.reshape(2, 3, 4)
print(F)
F[0].ndim

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


2

#### Indexação

Estude as seguintes indexações:

In [102]:
F1 = F[0]
print(F1)
F2 = F[1,0,:]
print(F2)
F3 = F[1,0,2]
print(F3)
F4 = F[1:2,0,2]
print(F4)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[12 13 14 15]
14
[14]


In [100]:
print(F1.shape)
print(F2.shape)
print(F3.shape)
print(F4.shape)

(3, 4)
(4,)
()
(1,)


### Exercício: Explique as dimensões de cada array:

F1: corresponde a matriz bidimiensional na posicção 1 do eixo espacial z, ou seja as coordenadas do plano x,y, para z = 1, ou seja, bidimensão (3, 4).

F2: corresponde a linha 0 da matriz F1, ou seja, dimensão 1.

F3: corresponde ao terceiro elemento da linha F2, ou seja, dimensão 0.

F4:

## Redução de eixo - aplicado a dois eixos simultâneos

Redução de eixo é quando a operação matricial resulta num array de menores dimensões.
Com essas operações, calcula-se estatística de colunas, linhas, etc.

### Exercício: Calcule o valor médio das matrizes F[0] e F[1], usando apenas um único comando F.mean(??)

In [117]:
print(F.mean((1,2)))

[ 5.5 17.5]


## Function - split - dados treino e validação

O exercício a seguir é para separar um conjunto de dados (dataset) em dois conjuntos, um
de treinamento e outro de validação.


Defina uma função que receba como entrada uma matriz, (dataset), onde cada linha é
referente a uma amostra e cada coluna referente a um atributo das amostras. O número total de
amostras é dado pelas linhas desta matriz.
Outro parâmetro de entrada é o fator de split `split_factor`, que é um número real entre 0 e 1. 
A saída da função são duas matrizes: amostras de treinamento e amostras de validação. 
A matriz de treinamento contrá o número de linhas dado por `split_factor` vezes o número de amostras.
A matriz de validação conterá o restante das amostras.

In [118]:
# Entrada, matriz contendo 10 amostras e 9 atributos
aa = np.arange(90).reshape(10,9)
print(aa)

[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]
 [27 28 29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42 43 44]
 [45 46 47 48 49 50 51 52 53]
 [54 55 56 57 58 59 60 61 62]
 [63 64 65 66 67 68 69 70 71]
 [72 73 74 75 76 77 78 79 80]
 [81 82 83 84 85 86 87 88 89]]


In [119]:
# Saída da função t,v = split(aa, 0.8)  # utilizado split_factor de 80%
t = np.arange(72).reshape(8,9)
print(t)

[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]
 [27 28 29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42 43 44]
 [45 46 47 48 49 50 51 52 53]
 [54 55 56 57 58 59 60 61 62]
 [63 64 65 66 67 68 69 70 71]]


In [120]:
v = np.arange(72,90).reshape(2,9)
print(v)

[[72 73 74 75 76 77 78 79 80]
 [81 82 83 84 85 86 87 88 89]]


In [129]:
# Evite o uso de laço explícito
# Não utilize outras bibliotecas além do NumPy
def split(dados, split_factor):
    '''
    divide a matriz dados em dois conjuntos:
    matriz train: split_factor * n. de linhas de dados
    matriz val: (1-split_factor) * n. de linhas de dados
    parametros entrada:
        dados: matriz de entrada
        split_factor: entre 0. e 1. - fator de divisão em duas matrizes
    parametros de saída:
        train : matriz com as linhas iniciais de dados
        val: matriz com as linhas restantes
    '''
    # insert your code here
    nlines = dados.shape[0]
    rows_t = int(split_factor*nlines)
    train, val  = dados[:rows_t,:],dados[rows_t:nlines,:]
    return train, val

t,v = split(aa, 0.8)
print('t=\n', t)
print('v=\n', v)

t=
 [[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]
 [27 28 29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42 43 44]
 [45 46 47 48 49 50 51 52 53]
 [54 55 56 57 58 59 60 61 62]
 [63 64 65 66 67 68 69 70 71]]
v=
 [[72 73 74 75 76 77 78 79 80]
 [81 82 83 84 85 86 87 88 89]]


### Exercício: Teste sua função com outros valores

In [137]:
t,v = split(B, 0.75)
print('t=\n', t)
print('v=\n', v)

t=
 [[10 11 12 13 14 15]
 [16 17 18 19 20 21]
 [22 23 24 25 26 27]]
v=
 [[28 29 30 31 32 33]]


# Fim do Notebook